In [3]:
# lista w Python:
a = [1, 2, 10]

# w tym przypadku pojemnik na 3 elementy, pod jedną nazwą

print(a)

[1, 2, 10]


In [5]:
# ale każdy element ma swój nr = indeks
print(a[0])
print(a[1])
print(a[2])

1
2
10


In [6]:
# suma elementów listy 'a'

b = a[0] + a[1] + a[2]
print(b)

13


In [7]:
# w module numpy jest DUŻO LEPSZA implementacja pojemników: macierzy, wektorów

import numpy as np

# wektor v1:
v1 = np.array( [1,2,10] )

print(v1) # 3 elements: 1,2,10
print( v1[0] ) # first element (index = 1)
print( v1[1] ) # first element (index = 2)
print( v1[2] ) # first element (index = 10)

print('Suma elementów v1:')

print( v1[0] + v1[1] + v1[2] )



[ 1  2 10]
1
2
10
Suma elementów v1:
13
[ 3  4 12]
[  1   4 100]
[ 3  6 30]


In [12]:
#Działania arytmetyczne na wektorach (najczęściej element-po-elemencie):

print("Elementy+2", v1, "=>", v1+2 )
print("Elementy do potęgi 2", v1, "=>", v1**2 )
print("Elementy x3", v1, "=>", 3*v1)

Elementy+2 [ 1  2 10] => [ 3  4 12]
Elementy do potęgi 2 [ 1  2 10] => [  1   4 100]
Elementy x3 [ 1  2 10] => [ 3  6 30]


In [15]:
v1 = np.array( [2,4,6] )

# nowy wektor z wynikami obliczeń, stary (v1) bez zmian
print("log10", np.log10(v1) )
print(v1)
v2 = np.log10(v1)
print(v2)

log10 [0.30103    0.60205999 0.77815125]
[2 4 6]
[0.30103    0.60205999 0.77815125]


In [16]:
# tworzenie serii/ciągów liczb (bezcenne przy tworzeniu wykresów):

v1 = np.linspace(0, 10, 5)
# start = 0
# end = 10
# ilość elementów, równo od siebie oddalonych (N) = 5

print(v1)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
v1 = np.linspace(0, 10) # domyślnie 50 elementów
print(v1)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [22]:
# Tablice/macierze

# Tworzenie maciecrzy 2x3 (2 kolumny, 3 wiersze)

m1 = np.array([[10,20],[30,40],[50,60]])
print(m1)
print("------")
# Addressing one element [row_index][column_index]:
print( m1[0][0] ) # 10 pierwszy wiersz i pierwsza kolumna
print( m1[1][1] ) # 40 drugi element i druga kolumna



[[10 20]
 [30 40]
 [50 60]]
------
10
40


In [ ]:
# wycinanie/wybieranie z macierzy kolumn (bardzo przydatne przy two
kolumna0 = m1[:,0]
kolumna1 = m1[:,1]
